---

name: Version bump and release
on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: "Version bump level"
        required: true
        options:
          - major
          - minor
          - patch
        default: patch

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Find last version
        id: get-version
        run: echo "version=$(jq --raw-output '.version' plugin.json)" >> $GITHUB_OUTPUT

      - uses: actions-ecosystem/action-bump-semver@v1
        id: semver
        with:
          current_version: ${{ steps.get-version.outputs.version }}
          level: ${{ github.event.inputs.level }}

      - name: Bump plugin.json version
        run: |
          jq ".version = \"${{ steps.semver.outputs.new_version }}\" | .longdescription = \"$(cat README.md)\"" plugin.json > plugin.json.tmp
          mv plugin.json.tmp plugin.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Bump version to ${{ steps.semver.outputs.new_version }}
          tagging_message: "v${{ steps.semver.outputs.new_version }}"

  release:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ needs.bump.outputs.version }}"
          name: "Frinja v${{ needs.bump.outputs.version }}"
          files: dist/*
          body: Install from Binary Ninja's plugin manager
